# Use the official Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the Python script to the container
COPY app.py .

# Set the default command to run the script
CMD ["python","app.py"]